# Generated by Django 4.1.3 on 2022-12-11 09:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0007_alter_employee_id_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial', models.IntegerField()),
                ('representation', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('document_type', models.IntegerField(choices=[(0, 'SKK'), (1, 'SP')], default=0)),
                ('status', models.IntegerField(choices=[(0, 'Canceled'), (1, 'Pending'), (2, 'Approved')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_documents', to='employee.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employee.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
