# Generated by Django 4.1.3 on 2022-12-11 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='serial',
        ),
    ]
