# Generated by Django 4.1.3 on 2022-12-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_remove_document_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.IntegerField(choices=[(0, 'SPK'), (1, 'SP')], default=0),
        ),
    ]
