# Generated by Django 4.1.3 on 2022-12-13 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_employee_signature'),
        ('leave_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employee.employee'),
        ),
    ]
