# Generated by Django 4.1.3 on 2022-12-13 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_request', '0002_alter_leavebalance_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavebalance',
            old_name='total_leave',
            new_name='total_balance',
        ),
    ]
