# Generated by Django 4.1.3 on 2022-12-13 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave_request', '0003_rename_total_leave_leavebalance_total_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavedetail',
            name='leave_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_details', to='leave_request.leaverequest'),
        ),
    ]
