# Generated by Django 4.1.3 on 2022-12-11 03:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_branch_created_at_branch_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='headquarter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='headquarter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
