# Generated by Django 4.1.3 on 2022-12-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Pria'), (1, 'Wanita')], default=0),
        ),
    ]
