# Generated by Django 4.1.3 on 2022-12-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='education',
            field=models.IntegerField(choices=[(0, 'SD'), (1, 'SMP'), (2, 'SMA'), (3, 'D1'), (4, 'D2'), (5, 'D3'), (6, 'D4'), (7, 'S1'), (8, 'S2'), (9, 'S3'), (10, 'Lainnya'), (11, 'Tidak Sekolah')], default=0),
        ),
    ]
