# Generated by Django 3.2.16 on 2022-12-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_employee_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
